config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get '/home', to: 'home#index'
  get '/about', to: 'home#about'
  get '/contact-us', to: 'home#contact_us'

  resources :posts do
    get :api_news, on: :collection
    resources :comments, except: :show
  end

  resources :categories, except: :show

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/address.rb
module Address
  def self.table_name_prefix
    "address_"
  end
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships
  has_many :posts, through: :post_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true

  validates :content, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :user

  after_create :assign_serial_number

  aasm column: :state do
    state :pending, initial: true
    state :submitted, :paid, :failed, :revoked, :delivered

    event :submit do
      transitions from: :pending, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :fail do
      transitions from: :pending, to: :failed
      transitions from: :submitted, to: :failed
    end

    event :revoke do
      transitions from: [:pending, :submitted], to: :revoked
      transitions from: [:delivered], to: :revoked

    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end

  private

  def assign_serial_number
    self.update(serial_number: "gem-#{id.to_s.rjust(9, '0')}")
  end


  # Create atleast 100 orders random users
  # Orders
  #
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  has_many :post_category_ships
  has_many :categories, through: :post_category_ships

  belongs_to :user
end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/student.rb
class Student < ApplicationRecord
  # has_one :student_image
  has_many :student_images
end

app/models/student_image.rb
class StudentImage < ApplicationRecord
  belongs_to :student
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  enum genre: { client: 0, admin: 1 }
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < ApplicationController

  def index
    regions = Address::Region.all
    render json: regions, each_serializer: RegionSerializer
  end

  def show
    region = Address::Region.find(params[:id])
    render json: region
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category deleted successfully'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully'
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to post_comments_path(@post)
  end


  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @names = ['mark', 'jasper', 'rex', 'jerome']
  end

  def about; end

  def contact_us; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'csv'

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :validate_post_owner, only: [:edit, :update, :destroy]

  def index
    @posts = Post.published.includes(:categories, :user)
                 .order(created_at: :DESC)

    respond_to do |format|
      format.html
      format.csv do
        csv_string = CSV.generate do |csv|
          csv << [
            User.human_attribute_name(:email),
            Post.human_attribute_name(:title),
            Post.human_attribute_name(:content),
            Post.human_attribute_name(:categories),
            Post.human_attribute_name(:created_at)
          ]

          @posts.each do |p|
            csv << [
              p.user&.email,
              p.title,
              p.content,
              p.categories.pluck(:name).join(','),
              p.created_at
            ]
          end
        end
        render plain: csv_string
      end
      format.json do
        render json: @posts.as_json
      end
      format.xml { render xml: @posts.as_json }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post update successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post update failed'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post destroyed successfully'
    redirect_to posts_path
  end

  def api_news
    api_key = ENV['API_NEWS_KEY']
    url = 'https://newsapi.org/v2/top-headlines'
    params = { 'apiKey': api_key, country: 'ph' }
    response = RestClient.get url, params: params

    response = JSON.parse(response)
    render json: response['articles']

    response['articles'].each do |articles|

    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image, category_ids: [])
  end

  def validate_post_owner
    return if current_user.genre == 'admin'

    unless @post.user == current_user
      flash[:alert] = 'the post not belongs to you'
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/categories/_form.html.erb
<% if category.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% category.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: category, url: path  do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/categories/edit.html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>

app/views/categories/index.html.erb
<%= link_to 'new', new_category_path, class: 'btn btn-sm btn-success' %>
<h1>Category List</h1>

<table class="table table-success table-striped">
  <thead>
  <td>Name</td>
  <td>ACTION</td>
  </thead>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to :edit, edit_category_path(category), class: 'btn btn-sm btn-warning' %>
        <%= button_to :delete, category_path(category), method: :delete, class: 'btn btn-sm btn-danger' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %></h1>
<h2>Edit Comment ID: <%= @comment.id %></h2>
<%= render partial: 'form', locals: { comment: @comment, path: post_comment_path(@post, @comment) } %>

app/views/comments/index.html.erb
<h1>Title <%= @post.title %></h1>
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.content %>(<%= comment.created_at %>)</li>
    <%= link_to 'Edit', edit_post_comment_path(@post, comment), class: 'btn btn-sm btn-warning' %>
    <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, class: 'btn btn-sm btn-danger' %>
  <% end %>
</ul>

<%= link_to 'Post List', posts_path %>

app/views/comments/new.html.erb
<!-- app/views/comments/new.html.erb -->

<h1>Title: <%= @post.title %></h1>
 <%= render partial: 'form', locals: { comment: @comment, path: post_comments_path(@post) } %>

app/views/home/about.html.erb
<h1>ABOUT US</h1>

app/views/home/contact_us.html.erb
<h1>Contact US</h1>

app/views/home/index.html.erb
<h1>HOME</h1>
<% if user_signed_in? %>
  <h2> Hello <%= current_user.email %> </h2>
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete%>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

<ul>
  <% @names.each do |name| %>
    <li><%= name %></li>
  <% end %>
</ul>

app/views/layouts/_flash_messages.html.erb
<div class="container-md">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <p class="notice"><%= flash[:notice] %></p>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <p class="alert"><%= flash[:alert] %></p>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'MY APP', root_path, class: 'nav-link' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav active">
      <li class="nav-item active">
        <%= link_to 'HOME', root_path, class: "nav-link #{ 'active' if action_name == 'index' }" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'POST LIST', posts_path, class: "nav-link #{ 'active' if action_name == 'index' && controller_name == 'posts' }" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'CATEGORY LIST', categories_path, class: "nav-link #{ 'active' if action_name == 'index' && controller_name == 'categories' }" %>
      </li>

      <li class="nav-item">
        <%= link_to 'ABOUT US', about_path, class: "nav-link #{ 'active' if action_name == 'about' }" %>
      </li>
      <li class="nav-item">
        <%= link_to 'CONTACT US', contact_us_path, class: "nav-link #{ 'active' if action_name == 'contact_us' }" %>
      </li>
    </ul>
  </div>
</nav>
<%= @page %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
  <%= render partial: 'layouts/navbar' %>
  <%= render partial: 'layouts/flash_messages' %>
  <div class="container-md">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: post do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :content, class: 'form-label' %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <div>
    <%= form.file_field :image %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render partial: 'posts/form', locals: { post: @post } %>

app/views/posts/index.html.erb
<h1>Post List</h1>
<%= link_to 'Export', posts_path(format: :csv, page: params[:page]),class: 'btn btn-sm btn-primary' %>
<%= link_to 'CREATE NEW POST', new_post_path, class: 'btn btn-sm btn-success' %>
<table class="table table-success table-striped">
  <thead>
  <td>TITLE</td>
  <td>CREATION TIME</td>
  <td>AUTHOR</td>
  <td>CATEGORIES</td>
  <td>COMMENT COUNT</td>
  <td>IMAGE</td>
  <td>ACTION</td>
  </thead>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.created_at %></td>
      <td><%= post.user&.email %></td>
      <td><%= post.categories.pluck(:name).join(',') %></td>
      <td>
        <%= post.comments_count %>
      </td>
      <td><%= image_tag post.image.url if post.image.present? %></td>
      <td>
        <%= link_to 'DETAIL', post_path(post), class: 'btn btn-sm btn-primary' %>
        <% if current_user && (current_user == post.user || current_user.genre == 'admin') %>
          <%= link_to 'EDIT',
                      edit_post_path(post),
                      class: 'btn btn-sm btn-warning' %>
          <%= button_to 'Delete', post_path(post),
                        class: 'btn btn-sm btn-danger', method: :delete %>
        <% end %>
        <%= link_to 'Comments', post_comments_path(post), class: 'btn btn-sm btn-primary' %>
        <%= link_to 'New Comment', new_post_comment_path(post), class: 'btn btn-sm btn-success' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>New Post</h1>
<%= render partial: 'posts/form', locals: { post: @post } %>

app/views/posts/show.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold"><%= @post.title %></h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4"> <%= @post.content %></p>
    <p class="mb-4"> <%= @post.created_at %></p>
  </div>
</div>